### PR TITLE
Obtain webhooks interactions commands from @syjust

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
The webhook commands look like interesting commands to me, I would love to include them in the fork I'm working on, and include as many commands as possible for the best CLI experience!

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
As I'm working on reformatting the code, my branch will (most likely) be incompatible with any other branches/forks, including the main one.  As such, it'll be more than just the show-lists.js file that will be incompatible.

**Comment by mglover** [comment]
What kind of reformatting are you doing?

**Comment by vinyldarkscratch** [comment]
Making sure that each command follows the same format, using four spaces for all indents (where some files used two spaces, or tabs), running a beautifying script, and cleaning up some unused files and variables -- as such, until it's pulled into the main repository (assuming it will be), other branches might have a hard time getting pulled into this branch!

**Comment by mglover** [comment]
I just pulled and am looking through the log.  My git-fu is weak. Are 
you still looking to submit pull requests for some of these?  -la

**Comment by vinyldarkscratch** [comment]
I am, yes — in fact, I just submitted a new pull request to the main branch.  The card-details command and translations.js (respectively the refresh command as well) are what I was mainly working on, would you be willing to check them out?

**Pull request closed without merging**
